#!/bin/bash
# Generate one self-contained sbatch script per h5ad in an Oak dataset directory,
# sizing memory / CPUs / walltime per file from the nnz of X (read via h5ls, no python).
# Same job body as scripts/tabula-muris/gen.sh:
#   standardize -> fill empty batch strings with "missing" -> identify-columns,
# writes on $SCRATCH, syncs results back to Oak next to the source data.
# Scripts live on the Oak side too:  <dataset>/eca-pp/jobs/<stage>.sbatch
#
#   bash scripts/tome-mouse/gen.sh <dataset-dir> <species> [extra standardize flags...]
#   bash scripts/tome-mouse/gen.sh tome-mouse mm
#   bash scripts/tabula-muris/submit_all.sh tome-mouse      # everything not yet finished
#   bash scripts/tabula-muris/status.sh                     # one line per sample
#
# Per-file rules:
#   mem  = clamp(16 GB + nnz(X) * 0.12 GB per 1e6, 32 GB, 200 GB)
#          calibrated on tome-mouse MaxRSS: 442M nnz -> 40 GB, 252M -> 23 GB, 216M -> 20 GB
#   cpus = max(8, ceil(mem / 8))                               (normal partition: <= 8 GB/core)
#   time = 04:00:00 if mem <= 64 GB else 08:00:00              (442M nnz ran in 18 min)
#   samples with < 100 cells get --no-gate (standardize's default min-cells gate would
#   reject them with exit 2; these early-stage samples are deliberately tiny)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
TM="$REPO/scripts/tabula-muris"          # shared helpers
OAK_BASE=/home/users/chensj16/oak/data/sc
WORK_BASE="$SCRATCH/eca-pp-runs"
MODEL="${ECA_PP_AGENT_MODEL:-claude-sonnet-5}"
CLAUDE_CLI="${ECA_PP_CLAUDE_CLI:-$(command -v claude)}"
NAME_PREFIX="${ECA_NAME_PREFIX:-seurat_object_}"   # stripped from the file name -> sample id

ds="${1:?dataset dir name under $OAK_BASE, e.g. tome-mouse}"
species="${2:?species code, e.g. mm / hs}"
shift 2
extra_std="$*"

src_dir="$OAK_BASE/$ds"
[ -d "$src_dir" ] || { echo "no such dataset dir: $src_dir" >&2; exit 2; }
short="${ds#tabula-}"
jobs="$src_dir/eca-pp/jobs"
mkdir -p "$jobs"
cp "$HERE"/gen.sh "$TM"/submit_all.sh "$TM"/status.sh "$TM"/fill_missing.py "$jobs"/

ml load hdf5/1.14.4 2>/dev/null || true
command -v h5ls >/dev/null || { echo "h5ls not found (ml load hdf5)" >&2; exit 2; }

printf "%-8s %10s %12s %6s %5s %9s %s\n" sample cells nnz mem cpus time flags
n=0
for f in "$src_dir"/*.h5ad; do
  sample="$(basename "$f" .h5ad)"; sample="${sample#$NAME_PREFIX}"
  cells="$(h5ls "$f/obs" | awk '$1=="_index"{gsub(/[{}]/,"",$3); print $3}')"
  nnz="$(h5ls "$f/X" | awk '$1=="data"{gsub(/[{}]/,"",$3); sub(/\/.*/,"",$3); print $3}')"
  [ -n "$nnz" ] || nnz=0
  mem=$(( 16 + nnz * 12 / 100000000 )); [ $mem -lt 32 ] && mem=32; [ $mem -gt 200 ] && mem=200
  cpus=$(( (mem + 7) / 8 )); [ $cpus -lt 8 ] && cpus=8
  if [ $mem -le 64 ]; then time=04:00:00; else time=08:00:00; fi
  flags="$extra_std"
  if [ -n "$cells" ] && [ "$cells" -lt 100 ]; then flags="$flags --no-gate"; fi
  printf "%-8s %10s %12s %5sG %5s %9s %s\n" "$sample" "$cells" "$nnz" "$mem" "$cpus" "$time" "${flags:-}"

  work="$WORK_BASE/$ds/$sample"
  oak_out="$src_dir/eca-pp/$sample"
  mkdir -p "$work"
  cat > "$jobs/$sample.sbatch" <<EOF
#!/bin/bash
#SBATCH -J ecapp-$short-$sample
#SBATCH -p normal
#SBATCH --time=$time
#SBATCH --cpus-per-task=$cpus
#SBATCH --mem=${mem}GB
#SBATCH -o $work/slurm-%j.log
# generated by scripts/tome-mouse/gen.sh — do not edit by hand
# source: $f  cells=$cells  nnz=$nnz
set -uo pipefail

REPO=$REPO
SRC=$f
WORK=$work
OAK_OUT=$oak_out
export ECA_PP_CLAUDE_CLI=$CLAUDE_CLI
export ECA_PP_AGENT_MODEL=$MODEL

mkdir -p "\$WORK" "\$OAK_OUT"
cd "\$WORK"
: > status.txt
echo "job=\${SLURM_JOB_ID:-local} node=\$(hostname) start=\$(date -Is)" | tee -a status.txt

finish() {
  local rc=\$?
  echo "end=\$(date -Is) exit=\$rc" | tee -a status.txt
  # results live on \$SCRATCH; mirror everything back to Oak next to the source
  rsync -a "\$WORK"/ "\$OAK_OUT"/
  exit \$rc
}
trap finish EXIT

echo "== standardize \$SRC"
bash "\$REPO/run.sh" standardize "\$SRC" -o "\$WORK/standardize" --species $species $flags
rc=\$?
echo "standardize exit=\$rc" | tee -a status.txt
[ \$rc -eq 0 ] || exit \$rc

echo "== fill empty batch strings with 'missing'"
bash "\$REPO/run.sh" python "\$REPO/scripts/tabula-muris/fill_missing.py" "\$WORK/standardize/standardized.h5ad"
rc=\$?
echo "fill-missing exit=\$rc" | tee -a status.txt
[ \$rc -eq 0 ] || exit \$rc

echo "== identify-columns"
bash "\$REPO/run.sh" identify-columns "\$WORK/standardize/standardized.h5ad" \\
     -o "\$WORK/identify_columns" --model "\$ECA_PP_AGENT_MODEL"
rc=\$?
echo "identify-columns exit=\$rc" | tee -a status.txt
exit \$rc
EOF
  n=$((n+1))
done
echo "generated $n sbatch scripts under $jobs/ (species=$species, extra standardize flags: '${extra_std:-none}')"
