#!/bin/bash
# Generate one self-contained sbatch script per h5ad in an Oak dataset directory.
# Each job: standardize -> fill empty batch strings with "missing" -> identify-columns,
# writes on $SCRATCH, syncs results back to Oak next to the source data.
# Scripts live on the Oak side too:  <dataset>/eca-pp/jobs/<organ>.sbatch
# (plus copies of gen.sh / submit_all.sh / status.sh / fill_missing.py).
#
#   bash scripts/tabula-muris/gen.sh <dataset-dir> <species> [extra standardize flags...]
#   bash scripts/tabula-muris/gen.sh tabula-muris-senis-drop mm
#   bash scripts/tabula-muris/gen.sh tabula-sapiens hs
#   sbatch $OAK/data/sc/<dataset-dir>/eca-pp/jobs/<organ>.sbatch
#   bash scripts/tabula-muris/submit_all.sh <dataset-dir>     # everything not yet finished
#
# Resources: sized per file — mem = clamp(24 GB per GB of h5ad, ECA_JOB_MEM_MIN=64, ECA_JOB_MEM_MAX=240),
# cpus = mem/8 (normal partition allows 8 GB/core), time ECA_JOB_TIME (default 04:00:00).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
OAK_BASE=/home/users/chensj16/oak/data/sc
WORK_BASE="$SCRATCH/eca-pp-runs"
MODEL="${ECA_PP_AGENT_MODEL:-claude-sonnet-5}"
# The default backend is HARNESS=openai (Doubao); a claude-* model only works
# through HARNESS=claude, so pin the backend alongside the model.
HARNESS="${HARNESS:-claude}"
CLAUDE_CLI="${ECA_PP_CLAUDE_CLI:-$(command -v claude)}"
MEM_MIN="${ECA_JOB_MEM_MIN:-64}"; MEM_MAX="${ECA_JOB_MEM_MAX:-240}"; TIME="${ECA_JOB_TIME:-04:00:00}"

ds="${1:?dataset dir name under $OAK_BASE, e.g. tabula-muris-senis-drop}"
species="${2:?species code, e.g. mm / hs}"
shift 2
extra_std="$*"

src_dir="$OAK_BASE/$ds"
[ -d "$src_dir" ] || { echo "no such dataset dir: $src_dir" >&2; exit 2; }
short="${ds#tabula-}"                       # job-name prefix
jobs="$src_dir/eca-pp/jobs"
mkdir -p "$jobs"
cp "$HERE"/gen.sh "$HERE"/submit_all.sh "$HERE"/status.sh "$HERE"/fill_missing.py "$HERE"/update_tracker.py "$jobs"/

n=0
for f in "$src_dir"/*.h5ad; do
  organ="$(basename "$f" .h5ad | sed -E 's/^tms-(drop|facs)-//; s/_TSP1_30_.*$//')"
  size_gb=$(( ($(stat -c%s "$f") + 1073741823) / 1073741824 ))
  mem=$(( size_gb * 24 )); [ $mem -lt $MEM_MIN ] && mem=$MEM_MIN; [ $mem -gt $MEM_MAX ] && mem=$MEM_MAX
  CPUS=$(( (mem + 7) / 8 )); MEM="${mem}GB"
  work="$WORK_BASE/$ds/$organ"
  oak_out="$src_dir/eca-pp/$organ"
  mkdir -p "$work"
  cat > "$jobs/$organ.sbatch" <<EOF
#!/bin/bash
#SBATCH -J ecapp-$short-$organ
#SBATCH -p normal
#SBATCH --time=$TIME
#SBATCH --cpus-per-task=$CPUS
#SBATCH --mem=$MEM
#SBATCH -o $work/slurm-%j.log
# generated by scripts/tabula-muris/gen.sh — do not edit by hand
set -uo pipefail

REPO=$REPO
SRC=$f
WORK=$work
OAK_OUT=$oak_out
export ECA_PP_CLAUDE_CLI=$CLAUDE_CLI
export ECA_PP_AGENT_MODEL=$MODEL
export HARNESS=$HARNESS

mkdir -p "\$WORK" "\$OAK_OUT"
cd "\$WORK"
: > status.txt
echo "job=\${SLURM_JOB_ID:-local} node=\$(hostname) start=\$(date -Is)" | tee -a status.txt

finish() {
  local rc=\$?
  echo "end=\$(date -Is) exit=\$rc" | tee -a status.txt
  # results live on \$SCRATCH; mirror everything back to Oak next to the source
  rsync -a "\$WORK"/ "\$OAK_OUT"/
  exit \$rc
}
trap finish EXIT

echo "== standardize \$SRC"
bash "\$REPO/run.sh" standardize "\$SRC" -o "\$WORK/standardize" --species $species $extra_std
rc=\$?
echo "standardize exit=\$rc" | tee -a status.txt
[ \$rc -eq 0 ] || exit \$rc

echo "== fill empty batch strings with 'missing'"
bash "\$REPO/run.sh" python "\$REPO/scripts/tabula-muris/fill_missing.py" "\$WORK/standardize/standardized.h5ad"
rc=\$?
echo "fill-missing exit=\$rc" | tee -a status.txt
[ \$rc -eq 0 ] || exit \$rc

echo "== identify-columns"
bash "\$REPO/run.sh" identify-columns "\$WORK/standardize/standardized.h5ad" \\
     -o "\$WORK/identify_columns" --model "\$ECA_PP_AGENT_MODEL"
rc=\$?
echo "identify-columns exit=\$rc" | tee -a status.txt
exit \$rc
EOF
  n=$((n+1))
done
echo "generated $n sbatch scripts under $jobs/ (species=$species, extra standardize flags: '${extra_std:-none}')"
