#!/bin/bash
# ma-devheart (MaDevHeart human developing heart, 14 files split by Rounded.PCW): one sbatch per h5ad.
# Same job body as scripts/tome-mouse/gen.sh: standardize -> fill_missing -> identify-columns,
# work on $SCRATCH, rsync back to <dataset>/eca-pp/<sample>.
#
# Per-file rules (differences from tome-mouse):
#   species : hs (human fetal heart, no obs/species column) — pinned, never inferred
#   counts  : X = float counts, layers/counts identical, layers/logcounts also present;
#             layers/counts is auto-recognised (no --counts-layer)
#   mem     : anndata materialises X + both layers, so
#             clamp(16 GB + 3 * nnz(X) * 0.12 GB per 1e6, 32, 200)
#   cpus = max(8, ceil(mem/8)); time = 04:00 if mem <= 64 else 08:00
#   sample id = file name minus "MaDevHeart_" (PCW6 ... PCW22)
#
#   bash scripts/ma-devheart/gen.sh && bash scripts/tabula-muris/submit_all.sh ma-devheart
#   bash scripts/tabula-muris/status.sh
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
TM="$REPO/scripts/tabula-muris"
OAK_BASE=/home/users/chensj16/oak/data/sc
WORK_BASE="$SCRATCH/eca-pp-runs"
MODEL="${ECA_PP_AGENT_MODEL:-doubao-seed-2-1-turbo-260628}"
# Backend and model are pinned as a pair: HARNESS=openai drives Doubao. Switch both
# together (HARNESS=claude + ECA_PP_AGENT_MODEL=claude-sonnet-5) to use Claude;
HARNESS="${HARNESS:-openai}"   # claude also works in the container (node+CLI are bound in)
CLAUDE_CLI="${ECA_PP_CLAUDE_CLI:-$(command -v claude)}"
ds=ma-devheart; species=hs
src_dir="$OAK_BASE/$ds"; jobs="$src_dir/eca-pp/jobs"; mkdir -p "$jobs"
cp "$HERE"/gen.sh "$TM"/submit_all.sh "$TM"/status.sh "$TM"/fill_missing.py "$jobs"/
ml load hdf5/1.14.4 2>/dev/null || true
command -v h5ls >/dev/null || { echo "h5ls not found" >&2; exit 2; }
nnz_of() { h5ls "$1" 2>/dev/null | awk '$1=="data"{gsub(/[{}]/,"",$3); sub(/\/.*/,"",$3); print $3}'; }
printf "%-8s %8s %12s %5s %5s %9s\n" sample cells nnzX mem cpus time
n=0
for f in "$src_dir"/*.h5ad; do
  sample="$(basename "$f" .h5ad)"; sample="${sample#MaDevHeart_}"
  cells="$(h5ls "$f/obs" | awk '$1=="_index"{gsub(/[{}]/,"",$3); print $3}')"
  nnz="$(nnz_of "$f/X")"; [ -n "$nnz" ] || nnz=0
  mem=$(( 16 + 3 * nnz * 12 / 100000000 )); [ $mem -lt 32 ] && mem=32; [ $mem -gt 200 ] && mem=200
  cpus=$(( (mem + 7) / 8 )); [ $cpus -lt 8 ] && cpus=8
  if [ $mem -le 64 ]; then time=04:00:00; else time=08:00:00; fi
  flags=""
  if [ -n "$cells" ] && [ "$cells" -lt 100 ]; then flags="--no-gate"; fi
  printf "%-8s %8s %12s %4sG %5s %9s\n" "$sample" "$cells" "$nnz" "$mem" "$cpus" "$time"
  work="$WORK_BASE/$ds/$sample"; oak_out="$src_dir/eca-pp/$sample"; mkdir -p "$work"
  cat > "$jobs/$sample.sbatch" <<EOF
#!/bin/bash
#SBATCH -J ecapp-$ds-$sample
#SBATCH -p normal
#SBATCH --time=$time
#SBATCH --cpus-per-task=$cpus
#SBATCH --mem=${mem}GB
#SBATCH -o $work/slurm-%j.log
# generated by scripts/ma-devheart/gen.sh — source: $f cells=$cells nnzX=$nnz (x3 matrices)
set -uo pipefail
REPO=$REPO
SRC=$f
WORK=$work
OAK_OUT=$oak_out
export ECA_PP_CLAUDE_CLI=$CLAUDE_CLI
export ECA_PP_AGENT_MODEL=$MODEL
export HARNESS=$HARNESS
mkdir -p "\$WORK" "\$OAK_OUT"; cd "\$WORK"; : > status.txt
echo "job=\${SLURM_JOB_ID:-local} node=\$(hostname) start=\$(date -Is)" | tee -a status.txt
finish() { local rc=\$?; echo "end=\$(date -Is) exit=\$rc" | tee -a status.txt; rsync -a "\$WORK"/ "\$OAK_OUT"/; exit \$rc; }
trap finish EXIT
echo "== standardize \$SRC"
bash "\$REPO/run.sh" standardize "\$SRC" -o "\$WORK/standardize" --species $species $flags
rc=\$?; echo "standardize exit=\$rc" | tee -a status.txt; [ \$rc -eq 0 ] || exit \$rc
echo "== fill empty batch strings with 'missing'"
bash "\$REPO/run.sh" python "\$REPO/scripts/tabula-muris/fill_missing.py" "\$WORK/standardize/standardized.h5ad"
rc=\$?; echo "fill-missing exit=\$rc" | tee -a status.txt; [ \$rc -eq 0 ] || exit \$rc
echo "== identify-columns"
bash "\$REPO/run.sh" identify-columns "\$WORK/standardize/standardized.h5ad" -o "\$WORK/identify_columns" --model "\$ECA_PP_AGENT_MODEL"
rc=\$?; echo "identify-columns exit=\$rc" | tee -a status.txt; exit \$rc
EOF
  n=$((n+1))
done
echo "generated $n sbatch scripts under $jobs/"
