#!/bin/bash
# uniChondro (19 cartilage/chondrocyte studies): one sbatch per h5ad.
# Layout (since 2026-09-03): <ds>/{human,mouse,rat}/<sample>.h5ad, outputs next to each species
# folder as <ds>/<species>/eca-pp/<sample>, job scripts in <ds>/<species>/eca-pp/jobs/.
# 20_Lawrence_2025_skeletal was dropped from the collection (no raw counts anywhere public).
# Same job body as scripts/tome-mouse/gen.sh: standardize -> fill_missing -> identify-columns,
# work on $SCRATCH, rsync back to <dataset>/eca-pp/<sample>.
#
# Per-file rules (differences from tome-mouse):
#   species      : from the species FOLDER (human -> hs, mouse -> mm, rat -> rn); obs/species is only
#                  checked and a mismatch is printed (14_Wang_2025 says human but is rat)
#   counts layer : layers/counts is auto-recognised; files whose only layer is
#                  counts_recovered (stancounts output) get --counts-layer counts_recovered
#   mem          : clamp(16 GB + (nnz(X) + nnz(counts layer)) * 0.12 GB per 1e6, 32, 200)
#                  (every file carries X AND a counts layer, so both are materialised)
#   cpus = max(8, ceil(mem/8)); time = 04:00 if mem <= 64 else 08:00
#
#   bash scripts/uniChondro/gen.sh
#   for j in $OAK/.../uniChondro/{human,mouse,rat}/eca-pp/jobs/*.sbatch; do sbatch $j; done   # submit_all.sh
#   assumes <ds>/eca-pp/jobs, so submit per species folder by hand
#   bash scripts/tabula-muris/status.sh
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
TM="$REPO/scripts/tabula-muris"
OAK_BASE=/home/users/chensj16/oak/data/sc
WORK_BASE="$SCRATCH/eca-pp-runs"
MODEL="${ECA_PP_AGENT_MODEL:-doubao-seed-2-1-turbo-260628}"
# Backend and model are pinned as a pair: HARNESS=openai drives Doubao. Switch both
# together (HARNESS=claude + ECA_PP_AGENT_MODEL=claude-sonnet-5) to use Claude;
HARNESS="${HARNESS:-openai}"   # claude also works in the container (node+CLI are bound in)
CLAUDE_CLI="${ECA_PP_CLAUDE_CLI:-$(command -v claude)}"
ds=uniChondro
ds_dir="$OAK_BASE/$ds"
ml load hdf5/1.14.4 2>/dev/null || true
command -v h5ls >/dev/null || { echo "h5ls not found" >&2; exit 2; }

nnz_of() { h5ls "$1" 2>/dev/null | awk '$1=="data"{gsub(/[{}]/,"",$3); sub(/\/.*/,"",$3); print $3}'; }
printf "%-30s %8s %12s %12s %3s %-22s %5s %5s %9s\n" sample cells nnzX nnzL sp counts_layer mem cpus time
n=0
for f in "$ds_dir"/{human,mouse,rat}/*.h5ad; do
  [ -f "$f" ] || continue
  sample="$(basename "$f" .h5ad)"; src_dir="$(dirname "$f")"; spdir="$(basename "$src_dir")"
  jobs="$src_dir/eca-pp/jobs"; mkdir -p "$jobs"
  [ -f "$jobs/gen.sh" ] || cp "$HERE"/gen.sh "$TM"/submit_all.sh "$TM"/status.sh "$TM"/fill_missing.py "$jobs"/
  case "$spdir" in human) species=hs ;; mouse) species=mm ;; rat) species=rn ;; esac
  cells="$(h5ls "$f/obs" | awk '$1=="_index"{gsub(/[{}]/,"",$3); print $3}')"
  spname="$(h5ls -d "$f/obs/species/categories" | grep -A2 'Data:' | tr -d '\n' | sed 's/.*Data://' | tr -d ' "')"
  [ "$spname" = "$spdir" ] || echo "NOTE $sample: obs.species='$spname' but folder is '$spdir' (folder wins)" >&2
  layers="$(h5ls "$f/layers" | awk '{print $1}')"
  layer_flag=""; nnzL=0; lname="(auto)"
  if echo "$layers" | grep -qx counts; then lname=counts; nnzL="$(nnz_of "$f/layers/counts")"
  elif echo "$layers" | grep -qx counts_recovered; then lname=counts_recovered; layer_flag="--counts-layer counts_recovered"; nnzL="$(nnz_of "$f/layers/counts_recovered")"
  fi
  nnzX="$(nnz_of "$f/X")"; [ -n "$nnzX" ] || nnzX=0; [ -n "$nnzL" ] || nnzL=0
  tot=$(( nnzX + nnzL ))
  mem=$(( 16 + tot * 12 / 100000000 )); [ $mem -lt 32 ] && mem=32; [ $mem -gt 200 ] && mem=200
  cpus=$(( (mem + 7) / 8 )); [ $cpus -lt 8 ] && cpus=8
  if [ $mem -le 64 ]; then time=04:00:00; else time=08:00:00; fi
  flags="$layer_flag"
  if [ -n "$cells" ] && [ "$cells" -lt 100 ]; then flags="$flags --no-gate"; fi
  printf "%-30s %8s %12s %12s %3s %-22s %4sG %5s %9s\n" "$sample" "$cells" "$nnzX" "$nnzL" "$species" "$lname" "$mem" "$cpus" "$time"

  work="$WORK_BASE/$ds/$sample"; oak_out="$src_dir/eca-pp/$sample"; mkdir -p "$work"
  cat > "$jobs/$sample.sbatch" <<EOF
#!/bin/bash
#SBATCH -J ecapp-$ds-$sample
#SBATCH -p normal
#SBATCH --time=$time
#SBATCH --cpus-per-task=$cpus
#SBATCH --mem=${mem}GB
#SBATCH -o $work/slurm-%j.log
# generated by scripts/uniChondro/gen.sh — source: $f cells=$cells nnzX=$nnzX nnzL=$nnzL species=$spname
set -uo pipefail
REPO=$REPO
SRC=$f
WORK=$work
OAK_OUT=$oak_out
export ECA_PP_CLAUDE_CLI=$CLAUDE_CLI
export ECA_PP_AGENT_MODEL=$MODEL
export HARNESS=$HARNESS
mkdir -p "\$WORK" "\$OAK_OUT"; cd "\$WORK"; : > status.txt
echo "job=\${SLURM_JOB_ID:-local} node=\$(hostname) start=\$(date -Is)" | tee -a status.txt
finish() { local rc=\$?; echo "end=\$(date -Is) exit=\$rc" | tee -a status.txt; rsync -a "\$WORK"/ "\$OAK_OUT"/; exit \$rc; }
trap finish EXIT
echo "== standardize \$SRC"
bash "\$REPO/run.sh" standardize "\$SRC" -o "\$WORK/standardize" --species $species $flags
rc=\$?; echo "standardize exit=\$rc" | tee -a status.txt; [ \$rc -eq 0 ] || exit \$rc
echo "== fill empty batch strings with 'missing'"
bash "\$REPO/run.sh" python "\$REPO/scripts/tabula-muris/fill_missing.py" "\$WORK/standardize/standardized.h5ad"
rc=\$?; echo "fill-missing exit=\$rc" | tee -a status.txt; [ \$rc -eq 0 ] || exit \$rc
echo "== identify-columns"
bash "\$REPO/run.sh" identify-columns "\$WORK/standardize/standardized.h5ad" -o "\$WORK/identify_columns" --model "\$ECA_PP_AGENT_MODEL"
rc=\$?; echo "identify-columns exit=\$rc" | tee -a status.txt; exit \$rc
EOF
  n=$((n+1))
done
echo "generated $n sbatch scripts under $ds_dir/{human,mouse,rat}/eca-pp/jobs/"
