#!/bin/bash
# yushan (FIRES PBMC/CSF, human): one sbatch for overall_rebuilt.h5ad only.
# rebuild-cont-csf/CONT_CSF_rebuilt.h5ad is a subset of overall_rebuilt (same 4 GEO CSF samples), skipped.
# Same job body as scripts/tome-mouse/gen.sh: standardize -> fill_missing -> identify-columns,
# work on $SCRATCH, rsync back to <dataset>/eca-pp/<sample>.
#   bash scripts/yushan/gen.sh && sbatch $OAK_BASE/yushan/eca-pp/jobs/overall_rebuilt.sbatch
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
OAK_BASE=/home/users/chensj16/oak/data/sc
WORK_BASE="$SCRATCH/eca-pp-runs"
MODEL="${ECA_PP_AGENT_MODEL:-doubao-seed-2-1-turbo-260628}"
# Backend and model are pinned as a pair: HARNESS=openai drives Doubao. Switch both
# together (HARNESS=claude + ECA_PP_AGENT_MODEL=claude-sonnet-5) to use Claude;
HARNESS="${HARNESS:-openai}"   # claude also works in the container (node+CLI are bound in)
CLAUDE_CLI="${ECA_PP_CLAUDE_CLI:-$(command -v claude)}"
ds=yushan; species=hs
src_dir="$OAK_BASE/$ds"; jobs="$src_dir/eca-pp/jobs"; mkdir -p "$jobs"
cp "$HERE"/gen.sh "$REPO/scripts/tabula-muris"/{status.sh,fill_missing.py} "$jobs"/
ml load hdf5/1.14.4 2>/dev/null || true
for f in "$src_dir"/overall_rebuilt.h5ad; do
  sample="$(basename "$f" .h5ad)"
  cells="$(h5ls "$f/obs" | awk '$1=="_index"{gsub(/[{}]/,"",$3); print $3}')"
  nnz="$(h5ls "$f/X" | awk '$1=="data"{gsub(/[{}]/,"",$3); sub(/\/.*/,"",$3); print $3}')"
  mem=$(( 16 + nnz * 12 / 100000000 )); [ $mem -lt 32 ] && mem=32; [ $mem -gt 200 ] && mem=200
  cpus=$(( (mem + 7) / 8 )); [ $cpus -lt 8 ] && cpus=8
  if [ $mem -le 64 ]; then time=04:00:00; else time=08:00:00; fi
  echo "$sample cells=$cells nnz=$nnz mem=${mem}G cpus=$cpus time=$time"
  work="$WORK_BASE/$ds/$sample"; oak_out="$src_dir/eca-pp/$sample"; mkdir -p "$work"
  cat > "$jobs/$sample.sbatch" <<EOF
#!/bin/bash
#SBATCH -J ecapp-$ds-$sample
#SBATCH -p normal
#SBATCH --time=$time
#SBATCH --cpus-per-task=$cpus
#SBATCH --mem=${mem}GB
#SBATCH -o $work/slurm-%j.log
# generated by scripts/yushan/gen.sh — source: $f cells=$cells nnz=$nnz
set -uo pipefail
REPO=$REPO
SRC=$f
WORK=$work
OAK_OUT=$oak_out
export ECA_PP_CLAUDE_CLI=$CLAUDE_CLI
export ECA_PP_AGENT_MODEL=$MODEL
export HARNESS=$HARNESS
mkdir -p "\$WORK" "\$OAK_OUT"; cd "\$WORK"; : > status.txt
echo "job=\${SLURM_JOB_ID:-local} node=\$(hostname) start=\$(date -Is)" | tee -a status.txt
finish() { local rc=\$?; echo "end=\$(date -Is) exit=\$rc" | tee -a status.txt; rsync -a "\$WORK"/ "\$OAK_OUT"/; exit \$rc; }
trap finish EXIT
echo "== standardize \$SRC"
bash "\$REPO/run.sh" standardize "\$SRC" -o "\$WORK/standardize" --species $species
rc=\$?; echo "standardize exit=\$rc" | tee -a status.txt; [ \$rc -eq 0 ] || exit \$rc
echo "== fill empty batch strings with 'missing'"
bash "\$REPO/run.sh" python "\$REPO/scripts/tabula-muris/fill_missing.py" "\$WORK/standardize/standardized.h5ad"
rc=\$?; echo "fill-missing exit=\$rc" | tee -a status.txt; [ \$rc -eq 0 ] || exit \$rc
echo "== identify-columns"
bash "\$REPO/run.sh" identify-columns "\$WORK/standardize/standardized.h5ad" -o "\$WORK/identify_columns" --model "\$ECA_PP_AGENT_MODEL"
rc=\$?; echo "identify-columns exit=\$rc" | tee -a status.txt; exit \$rc
EOF
done
echo "generated under $jobs/"
