#!/bin/bash
# Re-run ONLY identify-columns on finished ECA-PP outputs, one sbatch each (e.g. after an
# identify-columns update). Reads <out>/standardize/standardized.h5ad and writes <out>/identify_columns
# in place; the step itself moves the previous result into <out>/identify_columns/.history/.
#   bash scripts/rerun-identify-columns.sh [--platform droplet|plate|microwell|split-pool] [--dry-run] <out>...
#   e.g. bash scripts/rerun-identify-columns.sh --platform split-pool ~/oak/data/sc/parse-5M/eca-pp/*/
# Memory: clamp(16 GB + 3 x the h5ad size, 32, 200); the step reads the whole h5ad.
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODEL="${ECA_PP_AGENT_MODEL:-doubao-seed-2-1-turbo-260628}"
# Backend and model are pinned as a pair: HARNESS=openai drives Doubao (ARK_API_KEY from the environment).
HARNESS="${HARNESS:-openai}"
PY="${ECA_PP_PYTHON:-/scratch/users/chensj16/venvs/eca-pp-ct/python}"
platform=auto; dry=
while [ $# -gt 0 ]; do
  case $1 in --platform) platform=$2; shift 2;; --dry-run) dry=1; shift;; *) break;; esac
done
stamp="$(date +%Y%m%d-%H%M%S)"
for out in "$@"; do
  out="${out%/}"; h5="$out/standardize/standardized.h5ad"
  [ -f "$h5" ] || { echo "skip $out (no standardize/standardized.h5ad)"; continue; }
  name="$(basename "$(dirname "$(dirname "$out")")")-$(basename "$out")"
  gb=$(( $(stat -c %s "$h5") / 1000000000 ))
  mem=$(( 16 + 3 * gb )); [ $mem -lt 32 ] && mem=32; [ $mem -gt 200 ] && mem=200
  job="$out/idc-rerun-$stamp.sbatch"
  cat > "$job" <<EOF
#!/bin/bash
#SBATCH -J ecapp-$name-idc
#SBATCH -p normal
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=${mem}GB
#SBATCH -o $out/slurm-idc-%j.log
# generated by scripts/rerun-identify-columns.sh on $stamp (platform $platform)
set -uo pipefail
export ECA_PP_PYTHON=$PY ECA_PP_AGENT_MODEL=$MODEL HARNESS=$HARNESS
cd "$out"
echo "job=\${SLURM_JOB_ID:-local} node=\$(hostname) start=\$(date -Is) rerun=identify-columns platform=$platform" | tee -a status.txt
bash "$REPO/run.sh" identify-columns "$h5" -o "$out/identify_columns" --platform $platform --model "\$ECA_PP_AGENT_MODEL"
rc=\$?
echo "identify-columns exit=\$rc" | tee -a status.txt
echo "end=\$(date -Is) exit=\$rc" | tee -a status.txt
exit \$rc
EOF
  if [ -n "$dry" ]; then echo "would submit $name (${mem} GB): $job"; else echo -n "submit $name (${mem} GB) -> "; sbatch "$job"; fi
done
