#!/bin/bash
# mouse-pansci (PanSci organismal aging atlas, 14 organs): one sbatch per organ h5ad.
# Layout: <ds>/<organ>/<organ>.h5ad (organ-level dirs also hold the original cellbrowser
# mtx/tsv sources), outputs at the dataset level as <ds>/eca-pp/<organ>, jobs in
# <ds>/eca-pp/jobs/ — the tabula-muris convention, not the per-species uniChondro one.
# Only <organ>/<organ>.h5ad is picked up, so all/full-dataset.h5ad (HVG-only, 5373 genes)
# is skipped.
#
# The h5ads were rebuilt from each organ's own full-gene matrix (55416 genes, raw counts
# in X, no layers) with obs pulled from all/full-dataset.h5ad and cells filtered at
# nGenes>500 & nCounts>800; obs carries a `batch` column ({date}_EXP{n}_{sub}).
#
# Same job body as scripts/uniChondro/gen.sh: standardize -> fill_missing -> identify-columns,
# work on $SCRATCH, rsync back to <ds>/eca-pp/<organ>.
#
#   mem  : clamp(16 GB + nnz(X) * 0.12 GB per 1e6, 32, 200)  — X only, no counts layer
#   cpus : max(8, ceil(mem/8)); time = 04:00 if mem <= 64 else 08:00
#
#   bash scripts/mouse-pansci/gen.sh
#   bash scripts/tabula-muris/submit_all.sh mouse-pansci
#   bash scripts/tabula-muris/status.sh
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
TM="$REPO/scripts/tabula-muris"
OAK_BASE=/home/users/chensj16/oak/data/sc
WORK_BASE="$SCRATCH/eca-pp-runs"
MODEL="${ECA_PP_AGENT_MODEL:-doubao-seed-2-1-turbo-260628}"
# Backend and model are pinned as a pair: HARNESS=openai drives Doubao. Switch both
# together (HARNESS=claude + ECA_PP_AGENT_MODEL=claude-sonnet-5) to use Claude.
HARNESS="${HARNESS:-openai}"
CLAUDE_CLI="${ECA_PP_CLAUDE_CLI:-$(command -v claude)}"
species=mm
ds=mouse-pansci
ds_dir="$OAK_BASE/$ds"
jobs="$ds_dir/eca-pp/jobs"
mkdir -p "$jobs"
[ -f "$jobs/gen.sh" ] || cp "$HERE"/gen.sh "$TM"/submit_all.sh "$TM"/status.sh "$TM"/fill_missing.py "$TM"/update_tracker.py "$jobs"/

ml load hdf5/1.14.4 2>/dev/null || true
command -v h5ls >/dev/null || { echo "h5ls not found" >&2; exit 2; }
nnz_of() { h5ls "$1" 2>/dev/null | awk '$1=="data"{gsub(/[{}]/,"",$3); sub(/\/.*/,"",$3); print $3}'; }

printf "%-12s %10s %14s %6s %5s %9s\n" organ cells nnzX mem cpus time
n=0
for f in "$ds_dir"/*/*.h5ad; do
  [ -f "$f" ] || continue
  organ="$(basename "$f" .h5ad)"
  dir="$(basename "$(dirname "$f")")"
  # <organ>/<organ>.h5ad and its per-genotype splits <organ>/<organ>_<genotype>.h5ad;
  # skips all/full-dataset.h5ad and any stray files
  case "$organ" in
    "$dir"|"$dir"_*) ;;
    *) continue ;;
  esac
  # with splits present, the combined file has already been processed — set
  # PANSCI_SPLITS_ONLY=1 to generate jobs for the per-genotype files only
  if [ "${PANSCI_SPLITS_ONLY:-0}" = 1 ] && [ "$organ" = "$dir" ]; then
    ls "$(dirname "$f")/${dir}"_*.h5ad >/dev/null 2>&1 && continue
  fi

  cells="$(h5ls "$f/obs" 2>/dev/null | awk '$1=="_index"{gsub(/[{}]/,"",$3); print $3}')"
  nnzX="$(nnz_of "$f/X")"; [ -n "$nnzX" ] || nnzX=0
  mem=$(( 16 + nnzX * 12 / 100000000 )); [ $mem -lt 32 ] && mem=32; [ $mem -gt 200 ] && mem=200
  cpus=$(( (mem + 7) / 8 )); [ $cpus -lt 8 ] && cpus=8
  if [ $mem -le 64 ]; then time=04:00:00; else time=08:00:00; fi
  printf "%-12s %10s %14s %5sG %5s %9s\n" "$organ" "$cells" "$nnzX" "$mem" "$cpus" "$time"

  work="$WORK_BASE/$ds/$organ"; oak_out="$ds_dir/eca-pp/$organ"; mkdir -p "$work"
  cat > "$jobs/$organ.sbatch" <<EOF
#!/bin/bash
#SBATCH -J ecapp-$ds-$organ
#SBATCH -p normal
#SBATCH --time=$time
#SBATCH --cpus-per-task=$cpus
#SBATCH --mem=${mem}GB
#SBATCH -o $work/slurm-%j.log
# generated by scripts/mouse-pansci/gen.sh — source: $f cells=$cells nnzX=$nnzX
set -uo pipefail
REPO=$REPO
SRC=$f
WORK=$work
OAK_OUT=$oak_out
export ECA_PP_CLAUDE_CLI=$CLAUDE_CLI
export ECA_PP_AGENT_MODEL=$MODEL
export HARNESS=$HARNESS
mkdir -p "\$WORK" "\$OAK_OUT"; cd "\$WORK"; : > status.txt
echo "job=\${SLURM_JOB_ID:-local} node=\$(hostname) start=\$(date -Is)" | tee -a status.txt
finish() { local rc=\$?; echo "end=\$(date -Is) exit=\$rc" | tee -a status.txt; rsync -a "\$WORK"/ "\$OAK_OUT"/; exit \$rc; }
trap finish EXIT
echo "== standardize \$SRC"
bash "\$REPO/run.sh" standardize "\$SRC" -o "\$WORK/standardize" --species $species
rc=\$?; echo "standardize exit=\$rc" | tee -a status.txt; [ \$rc -eq 0 ] || exit \$rc
echo "== fill empty batch strings with 'missing'"
bash "\$REPO/run.sh" python "\$REPO/scripts/tabula-muris/fill_missing.py" "\$WORK/standardize/standardized.h5ad"
rc=\$?; echo "fill-missing exit=\$rc" | tee -a status.txt; [ \$rc -eq 0 ] || exit \$rc
echo "== identify-columns"
bash "\$REPO/run.sh" identify-columns "\$WORK/standardize/standardized.h5ad" -o "\$WORK/identify_columns" --model "\$ECA_PP_AGENT_MODEL"
rc=\$?; echo "identify-columns exit=\$rc" | tee -a status.txt; exit \$rc
EOF
  n=$((n+1))
done
echo "generated $n sbatch scripts under $jobs/"
