#!/bin/bash
# Generate one self-contained sbatch script per h5ad for a dataset whose X is a DENSE
# HDF5 dataset (legacy anndata format, e.g. mca1.1: float32 X, compound obs/var).
# Job body is identical to scripts/tome-mouse/gen.sh:
#   standardize -> fill empty batch strings with "missing" -> identify-columns,
# writes on $SCRATCH, syncs results back to Oak next to the source data.
#
#   bash scripts/mca1.1/gen.sh <dataset-dir> <species> [extra standardize flags...]
#   bash scripts/mca1.1/gen.sh mca1.1 mm
#   bash scripts/tabula-muris/submit_all.sh mca1.1
#   bash scripts/tabula-muris/status.sh
#
# Per-file rules (dense X):
#   dense_gb = cells * genes * 4 B                       (float32, fully materialised on load)
#   mem  = clamp(ceil(dense_gb * 8), 32 GB, 200 GB)      (dense + sparse copies + counts layer + lognorm X)
#   cpus = max(8, ceil(mem / 8))                         (normal partition: <= 8 GB/core)
#   time = 04:00:00 if mem <= 64 GB else 12:00:00
#   samples with < 100 cells get --no-gate
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
TM="$REPO/scripts/tabula-muris"          # shared helpers
OAK_BASE=/home/users/chensj16/oak/data/sc
WORK_BASE="$SCRATCH/eca-pp-runs"
MODEL="${ECA_PP_AGENT_MODEL:-claude-sonnet-5}"
# The default backend is HARNESS=openai (Doubao); a claude-* model only works
# through HARNESS=claude, so pin the backend alongside the model.
HARNESS="${HARNESS:-claude}"
CLAUDE_CLI="${ECA_PP_CLAUDE_CLI:-$(command -v claude)}"

ds="${1:?dataset dir name under $OAK_BASE, e.g. mca1.1}"
species="${2:?species code, e.g. mm / hs}"
shift 2
extra_std="$*"

src_dir="$OAK_BASE/$ds"
[ -d "$src_dir" ] || { echo "no such dataset dir: $src_dir" >&2; exit 2; }
short="${ds#tabula-}"
jobs="$src_dir/eca-pp/jobs"
mkdir -p "$jobs"
cp "$HERE"/gen.sh "$TM"/submit_all.sh "$TM"/status.sh "$TM"/fill_missing.py "$jobs"/

ml load hdf5/1.14.4 2>/dev/null || true
command -v h5ls >/dev/null || { echo "h5ls not found (ml load hdf5)" >&2; exit 2; }

printf "%-22s %8s %7s %8s %6s %5s %9s %s\n" sample cells genes denseGB mem cpus time flags
n=0
for f in "$src_dir"/*.h5ad; do
  sample="$(basename "$f" .h5ad)"
  read -r cells genes < <(h5ls "$f" | awk '$1=="X"{gsub(/[{},]/," ",$0); print $3, $4}')
  [ -n "${cells:-}" ] && [ -n "${genes:-}" ] || { echo "cannot read dense X shape of $f" >&2; exit 2; }
  dense_mb=$(( cells * genes * 4 / 1000000 ))
  mem=$(( (dense_mb * 8 + 999) / 1000 )); [ $mem -lt 32 ] && mem=32; [ $mem -gt 200 ] && mem=200
  cpus=$(( (mem + 7) / 8 )); [ $cpus -lt 8 ] && cpus=8
  if [ $mem -le 64 ]; then time=04:00:00; else time=12:00:00; fi
  flags="$extra_std"
  if [ "$cells" -lt 100 ]; then flags="$flags --no-gate"; fi
  printf "%-22s %8s %7s %8.2f %5sG %5s %9s %s\n" "$sample" "$cells" "$genes" "$(echo "$dense_mb/1000" | bc -l)" "$mem" "$cpus" "$time" "${flags:-}"

  work="$WORK_BASE/$ds/$sample"
  oak_out="$src_dir/eca-pp/$sample"
  mkdir -p "$work"
  cat > "$jobs/$sample.sbatch" <<EOF
#!/bin/bash
#SBATCH -J ecapp-$short-$sample
#SBATCH -p normal
#SBATCH --time=$time
#SBATCH --cpus-per-task=$cpus
#SBATCH --mem=${mem}GB
#SBATCH -o $work/slurm-%j.log
# generated by scripts/mca1.1/gen.sh — do not edit by hand
# source: $f  cells=$cells  genes=$genes  dense_mb=$dense_mb
set -uo pipefail

REPO=$REPO
SRC=$f
WORK=$work
OAK_OUT=$oak_out
export ECA_PP_CLAUDE_CLI=$CLAUDE_CLI
export ECA_PP_AGENT_MODEL=$MODEL
export HARNESS=$HARNESS

mkdir -p "\$WORK" "\$OAK_OUT"
cd "\$WORK"
: > status.txt
echo "job=\${SLURM_JOB_ID:-local} node=\$(hostname) start=\$(date -Is)" | tee -a status.txt

finish() {
  local rc=\$?
  echo "end=\$(date -Is) exit=\$rc" | tee -a status.txt
  # results live on \$SCRATCH; mirror everything back to Oak next to the source
  rsync -a "\$WORK"/ "\$OAK_OUT"/
  exit \$rc
}
trap finish EXIT

echo "== standardize \$SRC"
bash "\$REPO/run.sh" standardize "\$SRC" -o "\$WORK/standardize" --species $species $flags
rc=\$?
echo "standardize exit=\$rc" | tee -a status.txt
[ \$rc -eq 0 ] || exit \$rc

echo "== fill empty batch strings with 'missing'"
bash "\$REPO/run.sh" python "\$REPO/scripts/tabula-muris/fill_missing.py" "\$WORK/standardize/standardized.h5ad"
rc=\$?
echo "fill-missing exit=\$rc" | tee -a status.txt
[ \$rc -eq 0 ] || exit \$rc

echo "== identify-columns"
bash "\$REPO/run.sh" identify-columns "\$WORK/standardize/standardized.h5ad" \\
     -o "\$WORK/identify_columns" --model "\$ECA_PP_AGENT_MODEL"
rc=\$?
echo "identify-columns exit=\$rc" | tee -a status.txt
exit \$rc
EOF
  n=$((n+1))
done
echo "generated $n sbatch scripts under $jobs/ (species=$species, extra standardize flags: '${extra_std:-none}')"
