#!/bin/bash
# Re-run ONLY identify-columns for every sample of a dataset whose full job already finished
# with exit 0 (e.g. after an identify-columns code update). standardize output is kept; the
# previous identify_columns/ dir is moved aside as identify_columns.prev-<timestamp>/ on both
# $SCRATCH and Oak; status.txt gets a new "identify-columns exit=" + "end= exit=" line so
# status.sh / update_tracker.py / submit_all.sh see the latest run.
#   bash scripts/mca1.1/rerun_idc.sh <dataset-dir> [--dry-run]
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
OAK_BASE=/home/users/chensj16/oak/data/sc
WORK_BASE="$SCRATCH/eca-pp-runs"
MODEL="${ECA_PP_AGENT_MODEL:-claude-sonnet-5}"
# The default backend is HARNESS=openai (Doubao); a claude-* model only works
# through HARNESS=claude, so pin the backend alongside the model.
HARNESS="${HARNESS:-claude}"
CLAUDE_CLI="${ECA_PP_CLAUDE_CLI:-$(command -v claude)}"
ds="${1:?dataset dir}"; dry="${2:-}"
short="${ds#tabula-}"
jobs="$OAK_BASE/$ds/eca-pp/jobs"
stamp="$(date +%Y%m%d-%H%M%S)"
n=0
for st in "$WORK_BASE/$ds"/*/status.txt; do
  work="$(dirname "$st")"; sample="$(basename "$work")"
  grep -q '^end=.* exit=0$' "$st" || { echo "skip $sample (not finished ok)"; continue; }
  [ -f "$work/standardize/standardized.h5ad" ] || { echo "skip $sample (no standardized.h5ad)"; continue; }
  if squeue --me -h -o %j | grep -qx "ecapp-$short-$sample-idc"; then echo "skip $sample (queued)"; continue; fi
  cat > "$jobs/$sample.idc.sbatch" <<EOF
#!/bin/bash
#SBATCH -J ecapp-$short-$sample-idc
#SBATCH -p normal
#SBATCH --time=01:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=32GB
#SBATCH -o $work/slurm-idc-%j.log
# generated by scripts/mca1.1/rerun_idc.sh — identify-columns only, re-run on $stamp
set -uo pipefail
REPO=$REPO
WORK=$work
OAK_OUT=$OAK_BASE/$ds/eca-pp/$sample
export ECA_PP_CLAUDE_CLI=$CLAUDE_CLI
export ECA_PP_AGENT_MODEL=$MODEL
export HARNESS=$HARNESS
cd "\$WORK"
echo "job=\${SLURM_JOB_ID:-local} node=\$(hostname) start=\$(date -Is) rerun=identify-columns" | tee -a status.txt
finish() {
  local rc=\$?
  echo "end=\$(date -Is) exit=\$rc" | tee -a status.txt
  rsync -a "\$WORK"/ "\$OAK_OUT"/
  exit \$rc
}
trap finish EXIT
[ -d "\$WORK/identify_columns" ] && mv "\$WORK/identify_columns" "\$WORK/identify_columns.prev-$stamp"
echo "== identify-columns (re-run) \$WORK/standardize/standardized.h5ad"
bash "\$REPO/run.sh" identify-columns "\$WORK/standardize/standardized.h5ad" \\
     -o "\$WORK/identify_columns" --model "\$ECA_PP_AGENT_MODEL"
rc=\$?
echo "identify-columns exit=\$rc" | tee -a status.txt
exit \$rc
EOF
  n=$((n+1))
  if [ "$dry" = "--dry-run" ]; then echo "would submit $sample"; else echo -n "submit $sample -> "; sbatch "$jobs/$sample.idc.sbatch"; fi
done
echo "$n identify-columns re-run jobs"
